# Generated by Django 2.2.2 on 2019-07-01 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('bank_name', models.CharField(max_length=50)),
                ('bank_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('bank_id',),
            },
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('ifsc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.Banks')),
            ],
            options={
                'ordering': ('ifsc',),
            },
        ),
    ]
